# Generated by Django 5.2.3 on 2025-06-17 08:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RehostedMedia",
            fields=[
                (
                    "media_guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="The unique identifier used in the public URL.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="The absolute path to the processed audio file on the shared media volume.",
                        max_length=1024,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        default="audio/mpeg",
                        help_text="The MIME type of the audio file.",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
