# Generated by Django 5.2.3 on 2025-06-16 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RehostedPodcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_rss_url", models.URLField(unique=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "artwork_url",
                    models.URLField(blank=True, max_length=1024, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="RehostedEpisode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.CharField(
                        help_text="Unique episode ID from source RSS.",
                        max_length=512,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("pub_date_iso", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("absolute_file_path", models.CharField(max_length=1024)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "audio_file_size_bytes",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "podcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="rehost_app.rehostedpodcast",
                    ),
                ),
            ],
        ),
    ]
