# Generated by Django 5.2.4 on 2025-07-19 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="episode",
            name="rehosted_audio_url",
        ),
    ]
