# Generated by Django 5.2.4 on 2025-08-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0002_remove_episode_rehosted_audio_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="max_episodes",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Maximum number of episodes to keep for this podcast.",
            ),
        ),
    ]
