# Generated by Django 5.2.4 on 2025-09-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0003_podcast_max_episodes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="max_episodes",
        ),
        migrations.AddField(
            model_name="podcast",
            name="retain_all_episodes",
            field=models.BooleanField(
                default=False,
                help_text="If True, older episodes will not be deleted, overriding the global episode limit.",
            ),
        ),
    ]
