# Generated by Django 5.0.7 on 2025-09-25 08:21

from django.db import migrations

def set_retain_all_episodes(apps, schema_editor):
    Podcast = apps.get_model('podcasts', 'Podcast')
    Podcast.objects.update(retain_all_episodes=True)

class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0004_remove_podcast_max_episodes_and_more'),
    ]

    operations = [
        migrations.RunPython(set_retain_all_episodes),
    ]