# Generated by Django 5.2.4 on 2025-12-27 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0005_set_retain_all_episodes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="retain_all_episodes",
        ),
    ]
