# Generated by Django 5.2.4 on 2026-02-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0006_remove_podcast_retain_all_episodes"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="max_episodes",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Maximum number of episodes to keep for this podcast. If set to 0, all episodes will be retained.",
            ),
        ),
    ]
