# Generated by Django 5.2.4 on 2026-04-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0007_podcast_max_episodes"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="disable_ai_processing",
            field=models.BooleanField(
                default=False,
                help_text="If True, AI analysis will be skipped and original audio will be rehosted as-is.",
            ),
        ),
    ]
