# Generated by Django 5.2.4 on 2026-07-01 05:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0008_episode_disable_ai_processing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="rehosted_media_id",
            field=models.UUIDField(
                blank=True,
                default=uuid.uuid4,
                help_text="ID of the rehosted media in the rehost_app database.",
                null=True,
            ),
        ),
    ]
