# Generated by Django 5.2.4 on 2026-07-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0009_alter_episode_rehosted_media_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="duration_seconds",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Duration of the rehosted audio file in seconds.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="podcast",
            name="author",
            field=models.CharField(
                blank=True,
                help_text="Author of the podcast.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="podcast",
            name="description",
            field=models.TextField(
                blank=True, help_text="Description of the podcast.", null=True
            ),
        ),
    ]
