# Generated by Django 5.2.4 on 2026-09-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0010_episode_duration_seconds_podcast_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="processing_metrics",
            field=models.JSONField(
                blank=True,
                help_text="Telemetry and execution metrics recorded during episode processing.",
                null=True,
            ),
        ),
    ]
