# Generated by Django 5.2.3 on 2025-06-16 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Podcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the podcast, parsed from feed.",
                        max_length=255,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly slug, generated from title.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "rss_url",
                    models.URLField(
                        help_text="The unique URL of the podcast's RSS feed.",
                        unique=True,
                    ),
                ),
                ("artwork_url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.CharField(
                        help_text="Unique episode ID from RSS feed.",
                        max_length=512,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("pub_date", models.DateTimeField()),
                ("original_audio_url", models.URLField(max_length=1024)),
                (
                    "original_audio_path",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "processed_audio_path",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("QUEUED", "Queued"),
                            ("DOWNLOADING", "Downloading"),
                            ("TRANSCRIBING", "Transcribing"),
                            ("IDENTIFYING_ADS", "Identifying Ads"),
                            ("PROCESSING_AUDIO", "Processing Audio"),
                            ("COMPLETE", "Complete"),
                            ("FAILED", "Failed"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                ("failure_reason", models.TextField(blank=True, null=True)),
                (
                    "podcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="podcasts.podcast",
                    ),
                ),
            ],
        ),
    ]
