# Generated by Django 5.2.3 on 2025-06-26 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='rehosted_audio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='ad_segments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
