# Generated by Django 5.2.3 on 2025-06-27 11:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0002_auto_20250626_0823"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="episode",
            name="failure_reason",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="original_audio_path",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="processed_audio_path",
        ),
        migrations.AlterField(
            model_name="podcast",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
