# Generated by Django 5.2.3 on 2025-06-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0003_remove_episode_failure_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("QUEUED", "Queued"),
                    ("DOWNLOADING", "Downloading"),
                    ("ANALYZING", "Analyzing"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETE", "Complete"),
                    ("FAILED", "Failed"),
                ],
                default="NEW",
                max_length=20,
            ),
        ),
    ]
