# Generated by Django 5.2.3 on 2025-06-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0004_alter_episode_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="rehosted_media_id",
            field=models.UUIDField(
                blank=True,
                help_text="ID of the rehosted media in the rehost_app database.",
                null=True,
            ),
        ),
    ]
