# Generated by Django 5.2.3 on 2025-07-01 09:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0005_episode_rehosted_media_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="RehostedMedia",
            fields=[
                (
                    "media_guid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="The unique identifier used in the public URL.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="The absolute path to the processed audio file on the shared media volume.",
                        max_length=1024,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        default="audio/mpeg",
                        help_text="The MIME type of the audio file.",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="RehostedPodcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        help_text="A unique slug for the podcast, derived from its original RSS feed URL.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "original_rss_url",
                    models.URLField(
                        help_text="The original RSS feed URL of the podcast.",
                        max_length=1024,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the podcast.", max_length=500
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True,
                        help_text="The author of the podcast.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "artwork_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the podcast's artwork.",
                        max_length=1024,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the podcast.", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RehostedEpisode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.CharField(
                        help_text="The unique identifier (GUID) of the episode from the original RSS feed.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the episode.", max_length=500
                    ),
                ),
                (
                    "pub_date_iso",
                    models.CharField(
                        blank=True,
                        help_text="Publication date of the episode in ISO format.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the episode.", null=True
                    ),
                ),
                (
                    "absolute_file_path",
                    models.CharField(
                        help_text="The absolute path to the processed audio file on the shared media volume.",
                        max_length=1024,
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(
                        blank=True,
                        help_text="Duration of the episode in seconds.",
                        null=True,
                    ),
                ),
                (
                    "audio_file_size_bytes",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Size of the audio file in bytes.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "podcast",
                    models.ForeignKey(
                        help_text="The podcast this episode belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="podcasts.rehostedpodcast",
                    ),
                ),
            ],
            options={
                "unique_together": {("podcast", "guid")},
            },
        ),
    ]
