# Generated by Django 5.2.3 on 2025-07-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0006_rehostedmedia_rehostedpodcast_rehostedepisode"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="rehosted_audio_size",
            field=models.BigIntegerField(
                default=0, help_text="Size of the rehosted audio file in bytes."
            ),
        ),
    ]
