# Generated by Django 5.2.3 on 2025-07-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcasts", "0007_episode_rehosted_audio_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="last_polled",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
